# Generated by Django 5.0.6 on 2024-06-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['price_average'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
