# Generated by Django 5.0.6 on 2024-06-25 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='home.genre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_contractor',
            field=models.BooleanField(default=True, help_text='Check this box if you want hire a job instead make a freelancer', verbose_name='Is Contractor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.ManyToManyField(related_name='users', to='home.job'),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('details', models.CharField(max_length=600, verbose_name='Details')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
