# Generated by Django 5.0.6 on 2024-07-09 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_customuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='proposals_receive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
