# Generated by Django 5.0.6 on 2024-07-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_proposal_freelancer_alter_proposal_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(default='waiting', max_length=8, verbose_name='Status'),
        ),
    ]
